from . import account_chart_template
from . import account_card
from . import account_card_installment
from . import account_move
from . import account_move_line
from . import res_company
from . import res_config_setting
from . import account_payment
from . import res_partner
