{
    "name": "Account Payment Personal Loan",
    "version": "18.0.1.1.0",
    "category": "Accounting",
    "sequence": 14,
    "summary": "",
    "author": "ADHOC SA",
    "website": "www.adhoc.com.ar",
    "license": "AGPL-3",
    "images": [],
    "depends": ["card_installment", "account_debit_note", "account_payment_financial_surcharge"],
    "demo": [
        "demo/account_card.xml",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/res.groups.xml",
        "views/account_card.xml",
        "views/res_company_setting.xml",
        "views/account_move_views.xml",
        "views/account_payment.xml",
        "views/account_move_line_views.xml",
        "wizards/account_loan_register.xml",
        "wizards/account_loan_debt_report.xml",
        "wizards/account_loan_extra_charges.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
    "post_init_hook": "post_init_hook",
}
